services:
  mongodbatlas:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - gestion-network

  app:
    build: .
    container_name: gestion-colis-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodbatlas
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://mongodbatlas:27017/gestion_colis_db
    networks:
      - gestion-network

volumes:
  mongodb_data:

networks:
  gestion-network:
    external: true